name: Deploy App

on:
  push:
    branches: [main, dev/*]
    paths-ignore:
      - '**.tf'
      - '**.tfvars'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to deploy"
        required: true
        options:
          - dev

jobs:
  deployment-strategy:
    uses: ./.github/workflows/_trunk-config.yml
    with:
      event_name: ${{ github.event_name }}
      branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      workflow_dispatch_environment: ${{ github.event.inputs.environment }}

  deploy-dev:
    needs: deployment-strategy
    # Disabled
    if: |
      false &&
      github.event_name == 'workflow_dispatch' && 
      github.event.inputs.environment == 'dev'
    uses: ./.github/workflows/_app-deploy-job.yml
    with:
      environment: dev
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
      aws_region: ${{ vars.AWS_REGION }}
      s3_bucket: ${{ vars.S3_BUCKET }}
    permissions:
      id-token: write
      contents: read

  deploy-staging:
    needs: deployment-strategy
    # Disabled
    if: false && contains(fromJson(needs.deployment-strategy.outputs.environments), 'staging')
    uses: ./.github/workflows/_app-deploy-job.yml
    with:
      environment: staging
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
      aws_region: ${{ vars.AWS_REGION }}
      s3_bucket: ${{ vars.S3_BUCKET }}
    permissions:
      id-token: write
      contents: read

  deploy-production:
    needs: deployment-strategy
    if: contains(fromJson(needs.deployment-strategy.outputs.environments), 'production')
    uses: ./.github/workflows/_app-deploy-job.yml
    with:
      environment: production
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
      aws_region: ${{ vars.AWS_REGION }}
      s3_bucket: ${{ vars.S3_BUCKET }}
    permissions:
      id-token: write
      contents: read

  create-release:
    needs: deploy-production
    if: needs.deploy-production.result == 'success'
    permissions:
      contents: write
    uses: ./.github/workflows/_create-release-tag.yml
    with:
      environment: production
      commit_hash: ${{ needs.deploy-production.outputs.commit_hash }}